### ISSUE TITLE
does it has any side by side panel?

### ISSUE THREAD

**Issue by mohammadsaleh** [beygi/bootstrap-persian-datetimepicker#2]

**Comment by beygi** [comment]
could you provide a sample ?

**Comment by mohammadsaleh** [comment]
Like this below:
![capture](https://cloud.githubusercontent.com/assets/4922467/12003306/d7e9cd6e-ab10-11e5-8963-001db8efc73c.PNG)

**Comment by beygi** [comment]
I am afraid not . it has side by side feature for date and time but not two date calendars 
you can use Linked Pickers . please look at docs here : 
http://eonasdan.github.io/bootstrap-datetimepicker/#linked-pickers
